ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path
from cart import views
app_name = 'cart'
urlpatterns = [
    path('addcart/<int:i>', views.add_to_cart, name='addtocart'),
    path('cartview', views.cart_view, name='cartview'),
    path('cartrem/<int:s>', views.cart_remove, name='cartremove'),
    path('cartdel/<int:t>', views.delete_cart, name='cartdelete'),
    path('orderform', views.orderform, name='orderform'),
    path('success/<u>', views.payment_status, name='success'),
    path('orderview', views.order_view, name='orderview'),

]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('search/',include('search.urls')),
    path('cart/',include('cart.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.contrib import admin
from django.urls import path
app_name='search'
from search import views
urlpatterns = [
    path('', views.search_items,name='searchitems'),


]

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path
from shop import views
app_name = 'shop'
urlpatterns = [
    path('', views.allcategories, name='categories'),
    path('pro/<int:p>', views.allproducts, name='product'),
    path('details/<int:a>', views.details, name='details'),
    path('reg', views.register, name='reg'),
    path('logout', views.user_logout, name='logout'),
    path('login',views.user_login,name='login'),
    path('addpro',views.addproduct,name='addpro'),
    path('addcat',views.addcategory,name='addcat'),
    path('addstock/<int:h>',views.addstock,name='addstock'),

]

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateTimeField(auto_now_add=True)

    def totalprice(self):
       return self.product.price * self.quantity


class Orderdetails(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    no_of_items=models.IntegerField()
    address=models.TextField()
    phone=models.IntegerField()
    pin=models.IntegerField()


    order_id=models.CharField(max_length=20,blank=True)
    order_date=models.DateTimeField(auto_now_add=True)
    payment_status=models.CharField(default='pending',max_length=20)
    delivery_status=models.CharField(default='pending',max_length=20)


class Payment(models.Model):
    name=models.CharField(max_length=100)
    amount=models.IntegerField()
    order_id=models.CharField(max_length=30,blank=True)
    razorpay_payment_id=models.CharField(max_length=30,blank=True)
    paid=models.BooleanField(default=False)

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from cart.models import Cart,Payment,Orderdetails
from shop.models import Product
from django.contrib.auth.models import User
import razorpay
from django.contrib.auth import login
@login_required
def add_to_cart(request,i):
    p=Product.objects.get(id=i)
    u=request.user
    try:
        c=Cart.objects.get(user=u,product=p)
        if(p.stock>0):

            c.quantity+=1
            c.save()
            p.stock-=1
            p.save()
    except:
        if(p.stock>0):

            c=Cart.objects.create(user=u,product=p,quantity=1)
            c.save()
            p.stock-=1
            p.save()


    return redirect('cart:cartview')

def cart_view(request):
    u=request.user
    c=Cart.objects.filter(user=u)
    total=0
    for i in c:
        total+=i.quantity*i.product.price

    context={'cart':c,'total':total}
    return render(request,'cart.html',context)
@login_required
def cart_remove(request,s):
    p=Product.objects.get(id=s)
    u=request.user

    try:
        c=Cart.objects.get(user=u,product=p)
        if(c.quantity>1):
            c.quantity-=1
            c.save()
            p.stock+=1
            p.save()
        else:
            c.delete()
            p.stock += 1
            p.save()

    except:
        pass

    return redirect('cart:cartview')


def delete_cart(request,t):
    u=request.user
    p=Product.objects.get(id=t)
    c=Cart.objects.get(user=u,product=p)
    if(c.quantity>0):
        p.stock += c.quantity
        c.delete()
        p.save()
        return redirect('cart:cartview')

@login_required
def orderform(request):
    if(request.method=="POST"):
        address=request.POST['address']
        phone=request.POST['phone']
        pin=request.POST['pin']

        u=request.user

        c=Cart.objects.filter(user=u)

        total=0

        for i in c:
            total+=i.quantity*i.product.price
        total=int(total*100)
        print(total)

        client=razorpay.Client(auth=('rzp_test_m0oGroJJDxngbH','cQV6PHLCKLoa0NzwQTkN23kl'))

        response_payment=client.order.create(dict(amount=total,currency="INR"))
        # print(response_payment)
        order_id=response_payment['id'] #retrive order id from response
        order_status=response_payment['status'] #retrive order statu from response
        if(order_status=='created'):
            p=Payment.objects.create(name=u.username,amount=total,order_id=order_id)
            p.save()
            for i in c:
                o=Orderdetails.objects.create(product=i.product,user=u,no_of_items=i.quantity,address=address,phone=phone,pin=pin,order_id=order_id)
                o.save()
        else:
            pass
        response_payment['name']=u.username
        context={'payment':response_payment}

        return render(request,'payment.html',context)

    return render(request,'order.html')


from django.views.decorators.csrf import csrf_exempt
@csrf_exempt
def payment_status(request, u):
    user = User.objects.get(username=u)
    if(not request.user.is_authenticated):
        login(request,user)
    if(request.method=="POST"):
        response=request.POST
        print(response)
        print(u)
        param_dict={
            'razorpay_order_id':response['razorpay_order_id'],
            'razorpay_payment_id':response['razorpay_payment_id'],
            'razorpay_signature':response['razorpay_signature']
        }

        client = razorpay.Client(auth=('rzp_test_m0oGroJJDxngbH', 'cQV6PHLCKLoa0NzwQTkN23kl')) #to create a razorpay client


        try:
            status=client.utility.verify_payment_signature(param_dict)
            print(status)

            p=Payment.objects.get(order_id=response['razorpay_order_id'])
            p.razorpay_payment_id=response['razorpay_payment_id'] #adds the payment id after successful payment
            p.paid=True
            p.save()



            o=Orderdetails.objects.filter(user=user,order_id=response['razorpay_order_id'])
            for i in o:
                i.payment_status='paid'
                i.save()



            c=Cart.objects.filter(user=user)
            print(c)
            c.delete()

        except:
            pass
    return render(request,'payment_status.html',{'status':True})

@login_required
def order_view(request):
    u=request.user
    o=Orderdetails.objects.filter(user=u,payment_status='paid')
    context={'orders':o,}
    return render(request,'order_view.html',context)

ecommerce/search/views.py
from django.shortcuts import render


# Create your views here.
from shop.models import Product

from django.db.models import Q


def search_items(request):
    query = ''
    p = None

    if(request.method=="POST"):

        query = request.POST.get('q')

        if(query):

            p=Product.objects.filter(Q(name__icontains=query))


    return render(request,'search.html',{'pro':p,'k':query})

ecommerce/templates/addcategory.html
<!--<!DOCTYPE html>-->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center text-dark mt-3">Add Category</h1>
<form method="POST" enctype="multipart/form-data">


{% csrf_token %}
    <div class="mb-3 ms-4 text-light">
      <label class="form-label ">Name</label>
      <input type="text" class="form-control " name="n" placeholder="Enter the category name">
    </div>

    <div class="mb-3 ms-4 text-light">
      <label class="form-label ">Image</label>
      <input type="file" class="form-control " name="i">
    </div>

    <div class="mb-3 ms-4 text-light">
        <label class="form-label ">Description</label>
       <textarea class="form-control" name="d">Write Category description</textarea>
    </div>

    <div class="mt-3 ms-5">
            <input type="submit" value="SUBMIT">
    </div>
<br><br><br><br>


{% endblock %}

ecommerce/templates/addstock.html
<!--<!DOCTYPE html>-->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center text-dark mt-3">Add Stock</h1>
<form method="POST" enctype="multipart/form-data">

<center>
{% csrf_token %}
    <div class="mb-3 ms-4 w-25 text-light">
      <label class="form-label ">Enter the stock</label>
      <input type="number" class="form-control" value="{{pro.stock}}" name="n" placeholder="Enter stock">
    </div>


    <div class="mt-3 ms-5">
            <input type="submit" value="SUBMIT">
    </div>
    </center>
<br><br><br><br>


{% endblock %}

ecommerce/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css" integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>
    <header style="">
        <div class="container-fluid text-center">
            <img src="{% static 'images/a671ef222a6e136f8fe7fd9cfc97e57b.png' %}" height="60px" width="60px">

        </div>
                    <nav class="navbar navbar-expand-lg navbar-light bg-light mt-3">
              <div class="container-fluid">
                <a class="navbar-brand fs-4 fw-bold" href="#"> <img src="{% static 'images/a671ef222a6e136f8fe7fd9cfc97e57b.png' %}" height="40px" width="40px">Ecommerce</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav me-auto mb-2 mb-lg-0 fs-5 fw-bold ">
                    <li class="nav-item ms-4">
                      <a class="nav-link " aria-current="page" href="{% url 'shop:categories' %}">Home</a>
                    </li>

                       <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        All Categories
                      </a>
                      <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                          {% for i in links %}
                        <li><a class="dropdown-item" href="{% url 'shop:product' i.id %}">{{i.name}}</a></li>
                          {% endfor %}
                      </ul>

                    </li>
                    {% if user.is_authenticated %}
                    {% if user.is_superuser == False %}
                         <li class="nav-item ms-4">
                      <a class="nav-link " aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i></a>
                    </li>

                      <li class="nav-item ms-4">
                      <a class="nav-link " aria-current="page" href="{% url 'cart:orderview' %}">Your Orders</a>
                    </li>

                      {% else %}
                       <li class="nav-item ms-4">
                      <a class="nav-link " aria-current="page" href="{% url 'shop:addcat' %}">Add Categories</a>
                    </li>
                      <li class="nav-item ms-4">
                      <a class="nav-link " aria-current="page" href="{% url 'shop:addpro' %}">Add Products</a>
                    </li>
                      {% endif %}



                       <li class="nav-item ms-4">
                      <a class="nav-link " aria-current="page" href="{% url 'shop:logout' %}">Logout</a>
                    </li>
                        {% if count > 0 %}
                       <li class="nav-item ms-4">
                      <a class="nav-link " aria-current="page" href="{% url 'cart:cartview' %}"><i class="fa-solid fa-cart-shopping"></i><sup>{{count}}</sup></a>
                    </li>
                      {% else %}

                      {% endif %}
                    {% else %}




                       <li class="nav-item ms-4">
                      <a class="nav-link " aria-current="page" href="{% url 'shop:login' %}">Login</a>
                    </li>

                       <li class="nav-item ms-4">
                      <a class="nav-link " aria-current="page" href="{% url 'shop:reg' %}">Register</a>
                    </li>
                      {% endif %}
                  </ul>
                  <form class="d-flex" method="POST" action="{% url 'search:searchitems' %}">
                      {% csrf_token %}
                    <input class="form-control me-2 border-2 border-secondary" type="search" placeholder="Search" aria-label="Search" name="q">
                    <button class="btn btn-outline-dark " type="submit">Search</button>
                  </form>
                </div>
              </div>
            </nav>
    </header>



{% block content %}

{% endblock %}

<footer class="footer">

        <p class="text-center"><i class="fa-regular fa-copyright fs-6 me-1"></i>myshop@pvt.ltd</p>
</footer>



</body>
</html>

ecommerce/templates/cart.html
<!--<!DOCTYPE html>-->
{% extends 'base.html' %}
{% load static %}
{% block content %}

<div class="container mt-5 px-3" style="margin-bottom:100px;">
    <div class="row">
        <div class="col-sm-7">
            <table class="table table-bordered border-1 border-secondary shadow">
                <tr aria-colspan="6" class="text-center">
                    <th>cart items</th>
                </tr>
                
                {% for i in cart %}
                <tr>
                    <td><img src="{{i.product.image.url}}" height="100px" width="100px"></td>
                    <td>{{i.product.name}}</td>
                    <td>price:{{i.product.price}}<br>
                    Quantity:{{i.quantity}}</td>
                    <td>Total:{{i.totalprice}}</td>
                    <td class="text-center pt-5 ">
                        {% if i.product.stock > 0 %}
                        <a href="{% url 'cart:addtocart' i.product.id %}" ><i class="fa-solid fa-plus fs-5 text-light mx-1"></i></a>
                        <a href="{% url 'cart:cartremove' i.product.id %}" ><i class="fa-solid fa-minus fs-5 text-light mx-1"></i></a>
                        <a href="{% url 'cart:cartdelete' i.product.id %}" ><i class="fa-solid fa-trash fs-5 text-danger mx-1"></i></a>
                        {% else %}
                        <a href="{% url 'cart:cartremove' i.product.id %}" ><i class="fa-solid fa-minus fs-5 text-light mx-1"></i></a>
                        <a href="{% url 'cart:cartdelete' i.product.id %}" ><i class="fa-solid fa-trash fs-5 text-danger mx-1"></i></a>
                        {% endif %}

                    </td>

                </tr>
                {% endfor %}
            </table>
        </div>
        <div class="col-sm-4">
             <table class="table table-bordered border-1 border-secondary shadow">
                <tr colspan="4">
                    <th>check out</th>
                </tr>
                 <tr>
                     <td class="text-center">
                         Total price:{{total}}
                     </td>
                 </tr>
            </table>

            <a href="{% url 'cart:orderform' %}" class="btn btn-primary">Order now</a>&nbsp;&nbsp;&nbsp;&nbsp;

            <a href="{% url 'shop:categories' %}" class="btn btn-primary">Continue shopping</a>

        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
        <div class="col-12">

            <img src="{% static 'images/ecom.jpeg' %}" height="550px" width="100%">

        </div>
    </div>


<div class="container mb-5 " style="margin-top:150px;">
    <div class="row text-center">
        {% for j in cat %}
        <div class="col-sm-4 mx-auto">
            <div class="card mx-auto" style="width: 18rem;">
              <img src="{{j.image.url}}" height="220px" width="100%" class="card-img-top" alt="...">
              <div class="card-body text-center">
                <h5 class="card-title">{{j.name}}</h5>

                <a href="{% url 'shop:product' j.id %}" class="btn btn-primary">Products</a>
              </div>
            </div>
                    </div>
        {% endfor %}
    </div>
</div>





<div class="row " style="margin-bottom:100px;margin-top:150px;">
    <div class="col-12">
    <h3 class="text-center fw-bold mb-3">Lorem Ipsum </h3>
    <p style="text-align:justify;line-height:2;" class="px-5 fs-5"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>

    </div>
</div>





{% endblock %}

ecommerce/templates/details.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
<h2 class="text-center">view details</h2>

<div class="card mx-auto mb-3 bg-secondary " style="max-width: 600px;">
  <div class="row g-0">
    <div class="col-md-4 me-5">
      <img src="{{details.image.url}}" class="rounded-start p-3 " height="400px" width="100%" alt="..." style="mt-3 mb-3">
    </div>
    <div class="col-md-7 mt-5">
      <div class="card-body text-info">
        <h5 class="card-title m-2 ">Name:{{details.name}}</h5>
        <h5 class="card-text m-2">Description:{{details.desc}}</h5>
          <h5 class="card-text m-2">Price:{{details.price}}</h5>
        <h5 class="card-text m-2">Stock:{{details.stock}}</h5>
          <h5 class="card-text m-2">Available:{{details.available}}</h5>
          <h5 class="card-text m-2">Created:{{details.created}}</h5>
          <h5 class="card-text m-2">Updated:{{details.updated}}</h5>
        {% if user.is_superuser == True %}
          {% if details.stock > 0 %}
        <h5>product in stock</h5>
        <a href="{% url 'shop:addstock' details.id %}" class="btn btn-primary border-4">add stock</a>
          {% else %}
        <h5>Product Out Of Stock</h5>
         <a href="{% url 'shop:addstock' details.id %}" class="btn btn-primary border-4">add stock</a>
          {% endif %}
        {% else %}
          {% if details.stock > 0 %}
        <a href="{% url 'cart:addtocart' details.id %}" class="btn btn-primary border-4">add to cart</a>
        {% else %}
        <h5>Out Of Stock</h5>
        {% endif %}
      {% endif %}


    </div>
  </div>
</div>
</div>
</div>
{% endblock %}

ecommerce/templates/login.html
<!--<!DOCTYPE html>-->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center text-dark mt-3">Login</h1>
<form method="POST">


{% csrf_token %}
    <div class="mb-3 ms-4 me-5 text-light">
      <label class="form-label ">user name</label>
      <input type="text" class="form-control " name="u" placeholder="Enter the User name">
    </div>
    <div class="mb-3 ms-4 me-5 text-light">
      <label class="form-label ">Password</label>
      <input type="password" class="form-control " name="p" placeholder="Enter the Password">
    </div>
     <div class="mt-5 ms-5 me-5">
            <input type="submit" value="LOGIN">
    </div>


{% endblock %}

ecommerce/templates/order.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3" style="margin-bottom:100px;">

    <h2>orderform</h2>
    <form method="POST">
        {% csrf_token %}
          <div class="mb-3 ms-4 text-light">
      <label class="form-label ">Address</label>
      <input type="text" class="form-control " name="address" placeholder="Enter the Address">
    </div>
          <div class="mb-3 ms-4 text-light">
      <label class="form-label ">Phone</label>
      <input type="number" class="form-control " name="phone" placeholder="Enter the Phone number">
    </div>
          <div class="mb-3 ms-4 text-light">
      <label class="form-label ">Pin</label>
      <input type="number" class="form-control " name="pin" placeholder="Enter the Pin">
    </div>
             <div class="mb-3 ms-4 text-light">

      <input type="submit" class="form-control " >
    </div>
    </form>

</div>


{% endblock %}

ecommerce/templates/order_view.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">

    <div class="row text-center mx-auto">
        <h3>name of the coustomer: &nbsp; {{user.username}}</h3><br><br>
        {% for j in orders %}
        <div class="card mb-3 mx-auto" style="max-width: 540px;">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{j.product.image.url}}" class="img-fluid rounded-start" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">{{j.product.name}}</h5>
          <h5 class="card-title">{{j.product.price}}</h5>
           <h5 class="card-title">{{j.no_of_items}}</h5>
          <h5 class="card-title">{{j.address}}</h5>
          <h5 class="card-title">{{j.phone}}</h5>
          <h5 class="card-title">{{j.ordered_date}}</h5>
          <h5 class="card-title">{{j.delivery_status}}</h5>

      </div>
    </div>
  </div>
</div>
        {% endfor %}
    </div>
</div>

{% endblock %}

ecommerce/templates/payment.html
<!--<!DOCTYPE html>-->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 border border-1 border-primary bg-light" style="margin-bottom-100px">

    <form action="http://127.0.0.1:8000/cart/success/{{payment.name}}" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_m0oGroJJDxngbH" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
    data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
    data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
    data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{payment.name}}"
    data-prefill.email="ghis@gmail.com"
    data-theme.color="#F37254"
></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
</div>


{% endblock %}

ecommerce/templates/payment_status.html
<!--<!DOCTYPE html>-->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5 p-3 border border-1 border-primary bg-light" style="margin-bottom-100px">
{% if status == True %}

    <h1>payment success</h1>
{% else %}
    <h1>payment failed please try again</h1>
</div>
{% endif %}


{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="row">
        <div class="col-12">

            <img src="{{cat.image.url}}" height="550px" width="100%">

        </div>
    </div>




<div class="row " style="margin-bottom:100px;margin-top:150px;">
    <div class="col-12">
    <h3 class="text-center fw-bold mb-3">{{cat.name}} </h3>
    <p style="text-align:justify;line-height:2;" class="px-5 fs-5">{{cat.desc}}</p>

    </div>
</div>





<div class="container mb-5 " style="margin-top:150px;">
    <div class="row text-center">
        {% for j in pro %}
        <div class="col-sm-4 mx-auto">
            <div class="card mx-auto" style="width: 18rem;">
              <img src="{{j.image.url}}" height="220px" width="100%" class="card-img-top" alt="...">
              <div class="card-body text-center">
                <h5 class="card-title">{{j.name}}</h5>
                   <a href="{% url 'shop:details' j.id %}" class="btn btn-primary">Details</a>


              </div>
            </div>
                    </div>
        {% endfor %}
    </div>
</div>
{% endblock %}

ecommerce/templates/register.html
<!--<!DOCTYPE html>-->
{% extends 'base.html' %}
{% load static %}
{% block content %}
<h1 class="text-center text-dark mt-3">Register</h1>
<form method="POST">


{% csrf_token %}
    <div class="mb-3 ms-4 text-light">
      <label class="form-label ">user name</label>
      <input type="text" class="form-control " name="u" placeholder="Enter the User name">
    </div>
    <div class="mb-3 ms-4 text-light">
      <label class="form-label ">Password</label>
      <input type="password" class="form-control " name="p" placeholder="Enter the Password">
    </div>
    <div class="mb-3 ms-4 text-light">
      <label class="form-label ">Confirm Password</label>
      <input type="password" class="form-control " name="cp" placeholder="Enter the rePassword">
    </div>
    <div class="mb-3 ms-4 text-light">
      <label class="form-label ">First name</label>
      <input type="text" class="form-control " name="f" placeholder="Enter the First name">
    </div>
    <div class="mb-3 ms-4 text-light">
      <label class="form-label ">Last name</label>
      <input type="text" class="form-control " name="l" placeholder="Enter the Last name">
    </div>
    <div class="mb-3 ms-4 text-light">
      <label class="form-label ">Email</label>
      <input type="email" class="form-control " name="e" placeholder="Enter the Email">
    </div>
    <div class="mt-3 ms-5">
            <input type="submit" value="SUBMIT">
    </div>
<br><br><br><br>


{% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<!--<div class="row">-->
<!--        <div class="col-12">-->

<!--            <img src="{{cat.image.url}}" height="550px" width="100%">-->

<!--        </div>-->
<!--    </div>-->




<!--<div class="row " style="margin-bottom:100px;margin-top:150px;">-->
<!--    <div class="col-12">-->
<!--    <h3 class="text-center fw-bold mb-3">{{cat.name}} </h3>-->
<!--    <p style="text-align:justify;line-height:2;" class="px-5 fs-5">{{cat.desc}}</p>-->

<!--    </div>-->
<!--</div>-->


<h2>searched for {{k}}</h2>


<div class="container mb-5 " style="margin-top:150px;">
    {% if pro == None %}  <!--if no query is entered by the user-->
    <h2 class="text-center">No results found</h2>
    {% else %}
    <div class="row text-center ">
        {% for j in pro %}
        <div class="col-sm-4 mx-auto mb-4">
            <div class="card mx-auto" style="width: 18rem;">
              <img src="{{j.image.url}}" height="220px" width="100%" class="card-img-top" alt="...">
              <div class="card-body text-center">
                <h5 class="card-title">{{j.name}}</h5>
                   <a href="{% url 'shop:details' j.id %}" class="btn btn-primary">Details</a>


              </div>
            </div>
                    </div>
        {% empty %}         <!--if there is no products matching the entered query-->
        <h3 class="text-center">No results found</h3>
        {% endfor %}


    </div>
    {% endif %}

</div>
{% endblock %}